### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by waldyrious** [slashme/WikipediaGlobeAnimation#1]
README.md says:

> Frame 1000 of the animation is a very close copy of the official Wikipedia puzzle globe logo. The copyright of this logo belongs to the Wikimedia Foundation, so don't use it without permission.

However, this seems to contradict with the information on this blog post (and comments): https://blog.wikimedia.org/2014/10/24/wikimedia-logos-have-been-freed/

Can you get clarification from the people who provided you the 3D logo files?

**Comment by slashme** [comment]
Good point, it should instead say that it's licensed under CC, but is also the trademark of the WMF. I'll correct the text tomorrow.
